# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_user(object):
    def setupUi(self, add_user):
        add_user.setObjectName("add_user")
        add_user.resize(428, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_user)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(add_user)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(200, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.saveabtn = QtWidgets.QPushButton(self.groupBox)
        self.saveabtn.setGeometry(QtCore.QRect(160, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveabtn.setFont(font)
        self.saveabtn.setObjectName("saveabtn")
        self.naneEdit = QtWidgets.QLineEdit(self.groupBox)
        self.naneEdit.setGeometry(QtCore.QRect(30, 99, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.naneEdit.setFont(font)
        self.naneEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.naneEdit.setObjectName("naneEdit")
        self.passEdit = QtWidgets.QLineEdit(self.groupBox)
        self.passEdit.setGeometry(QtCore.QRect(30, 139, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passEdit.setFont(font)
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passEdit.setObjectName("passEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(230, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(230, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rePassEdit = QtWidgets.QLineEdit(self.groupBox)
        self.rePassEdit.setGeometry(QtCore.QRect(30, 179, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rePassEdit.setFont(font)
        self.rePassEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rePassEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rePassEdit.setObjectName("rePassEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(add_user)
        QtCore.QMetaObject.connectSlotsByName(add_user)

    def retranslateUi(self, add_user):
        _translate = QtCore.QCoreApplication.translate
        add_user.setWindowTitle(_translate("add_user", "Form"))
        self.label_4.setText(_translate("add_user", "اعادة كلمة المرور : "))
        self.saveabtn.setText(_translate("add_user", "حفظ"))
        self.label_2.setText(_translate("add_user", "الاسم : "))
        self.label_3.setText(_translate("add_user", "كلمة المرور : "))
        self.label.setText(_translate("add_user", "اضافة مستخدم جديد"))
