# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_action.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_action(object):
    def setupUi(self, add_action):
        add_action.setObjectName("add_action")
        add_action.resize(435, 479)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(add_action)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(add_action)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(add_action)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_detales = QtWidgets.QTextEdit(add_action)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_detales.setFont(font)
        self.textEdit_detales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_detales.setObjectName("textEdit_detales")
        self.verticalLayout.addWidget(self.textEdit_detales)
        self.label_3 = QtWidgets.QLabel(add_action)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(add_action)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.label_4 = QtWidgets.QLabel(add_action)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit_note = QtWidgets.QTextEdit(add_action)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_note.setFont(font)
        self.textEdit_note.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_note.setObjectName("textEdit_note")
        self.verticalLayout.addWidget(self.textEdit_note)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(add_action)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(add_action)
        QtCore.QMetaObject.connectSlotsByName(add_action)

    def retranslateUi(self, add_action):
        _translate = QtCore.QCoreApplication.translate
        add_action.setWindowTitle(_translate("add_action", "Form"))
        self.label.setText(_translate("add_action", "اضافة حدث "))
        self.label_2.setText(_translate("add_action", "تفاصيل الحدث : "))
        self.label_3.setText(_translate("add_action", "التاريخ : "))
        self.label_4.setText(_translate("add_action", "التعليق"))
        self.pushButton.setText(_translate("add_action", "حفظ"))
