# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_exam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_exam(object):
    def setupUi(self, add_exam):
        add_exam.setObjectName("add_exam")
        add_exam.resize(413, 277)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(add_exam)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(add_exam)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(add_exam)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.examEdit = QtWidgets.QLineEdit(add_exam)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.examEdit.setFont(font)
        self.examEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.examEdit.setObjectName("examEdit")
        self.verticalLayout.addWidget(self.examEdit)
        self.label_3 = QtWidgets.QLabel(add_exam)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(add_exam)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(add_exam)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(add_exam)
        QtCore.QMetaObject.connectSlotsByName(add_exam)

    def retranslateUi(self, add_exam):
        _translate = QtCore.QCoreApplication.translate
        add_exam.setWindowTitle(_translate("add_exam", "Form"))
        self.label.setText(_translate("add_exam", "اضافة امتحان جديد "))
        self.label_2.setText(_translate("add_exam", "اسم الامتحان : "))
        self.label_3.setText(_translate("add_exam", "التاريخ : "))
        self.pushButton.setText(_translate("add_exam", "حفظ"))
